/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import englishproject.Conceptos;

import englishproject.ManipulaListas;
import englishproject.Nodo;
import java.awt.Color;

/**
 *
 * @author mosh_
 */
public class VtnAltaConceptos extends javax.swing.JFrame
{

    public boolean flag = true;

    /**
     * Creates new form Principal
     */
    public VtnAltaConceptos()
    {
        initComponents();
        this.setResizable(false);
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JLabelLetra = new javax.swing.JLabel();
        txtconcepts = new javax.swing.JTextField();
        jButtonAñadir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldDefin = new javax.swing.JTextField();
        JLabelLetra1 = new javax.swing.JLabel();
        jTextFieldExample = new javax.swing.JTextField();
        JLabelLetra2 = new javax.swing.JLabel();
        JLabelLetra3 = new javax.swing.JLabel();
        txtword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("My Dictionary ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelTitulo1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabelTitulo1.setText("Add Concept");

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        JLabelLetra.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JLabelLetra.setText("Traslation");

        txtconcepts.setBackground(new java.awt.Color(255, 255, 204));
        txtconcepts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtconceptsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtconceptsKeyTyped(evt);
            }
        });

        jButtonAñadir.setBackground(new java.awt.Color(0, 102, 0));
        jButtonAñadir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAñadir.setText("Add");
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });
        jButtonAñadir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAñadirKeyPressed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(51, 0, 0));
        jButtonCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonCancelar.setText("Cancel");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTextFieldDefin.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldDefin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDefinKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDefinKeyTyped(evt);
            }
        });

        JLabelLetra1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JLabelLetra1.setText("Definition");

        jTextFieldExample.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldExample.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldExampleKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldExampleKeyTyped(evt);
            }
        });

        JLabelLetra2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JLabelLetra2.setText("Example");

        JLabelLetra3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JLabelLetra3.setText("Word");

        txtword.setBackground(new java.awt.Color(255, 255, 204));
        txtword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtwordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtwordKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonCancelar)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(JLabelLetra2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldExample, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JLabelLetra1)
                                        .addComponent(JLabelLetra3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(JLabelLetra, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtconcepts, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldDefin, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtword, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo1)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelLetra3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelLetra)
                    .addComponent(txtconcepts, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelLetra1)
                    .addComponent(jTextFieldDefin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelLetra2)
                    .addComponent(jTextFieldExample, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAñadir)
                    .addComponent(jButtonCancelar))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAñadirActionPerformed
    {//GEN-HEADEREND:event_jButtonAñadirActionPerformed
        String s[] = new String[1];
        s[0] = txtconcepts.getText().substring(0, 1).toUpperCase();
        Nodo aux = ManipulaListas.busca(VtnPrincipal.raiz, s, 0).getAbajo();
        Nodo aux1 = aux;
        do
        {
            if (aux1 == null)
            {
                break;
            }
            if (txtconcepts.getText().equals(aux1.getEtiqueta()))
            {
                flag = false;
                Mensaje.error(this, "This concept already exist");
                break;
            }
            aux1 = aux1.getSiguiente();
        } while (aux1 != aux);

        if (flag)
        {
            Conceptos obj = new Conceptos(txtword.getText(),txtconcepts.getText(),  jTextFieldDefin.getText(), jTextFieldExample.getText());
            Nodo n = new Nodo(String.valueOf(obj.getWord()), obj);
            s = new String[2];
            s[0] = obj.getWord().substring(0, 1).toUpperCase();
            s[1] = obj.getWord();
            VtnPrincipal.raiz = ManipulaListas.inserta(VtnPrincipal.raiz, s, 0, n, null);
            ManipulaListas.contConc++;
            Mensaje.exito(this, "Concept Add Succefull");
            jButtonCancelarActionPerformed(null);
        }
        flag = true;
    }//GEN-LAST:event_jButtonAñadirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelarActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelarActionPerformed
        
        CtrlInterfaz.habilita(true, jButtonAñadir);
        CtrlInterfaz.limpia(txtconcepts, jTextFieldDefin, jTextFieldExample);

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAñadirKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jButtonAñadirKeyPressed
    {//GEN-HEADEREND:event_jButtonAñadirKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            jButtonAñadirActionPerformed(null);
        }
    }//GEN-LAST:event_jButtonAñadirKeyPressed

    private void txtconceptsKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtconceptsKeyTyped
    {//GEN-HEADEREND:event_txtconceptsKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_txtconceptsKeyTyped

    private void txtconceptsKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtconceptsKeyPressed
    {//GEN-HEADEREND:event_txtconceptsKeyPressed
        Validaciones.enter(this, evt, jTextFieldDefin);
    }//GEN-LAST:event_txtconceptsKeyPressed

    private void jTextFieldDefinKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldDefinKeyPressed
    {//GEN-HEADEREND:event_jTextFieldDefinKeyPressed
        Validaciones.enter(this, evt, jTextFieldExample);
    }//GEN-LAST:event_jTextFieldDefinKeyPressed

    private void jTextFieldDefinKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldDefinKeyTyped
    {//GEN-HEADEREND:event_jTextFieldDefinKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDefinKeyTyped

    private void jTextFieldExampleKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldExampleKeyPressed
    {//GEN-HEADEREND:event_jTextFieldExampleKeyPressed
        Validaciones.enter(this, evt, jButtonAñadir);
    }//GEN-LAST:event_jTextFieldExampleKeyPressed

    private void jTextFieldExampleKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldExampleKeyTyped
    {//GEN-HEADEREND:event_jTextFieldExampleKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldExampleKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        //cargaComboLetras();
    }//GEN-LAST:event_formWindowOpened

    private void txtwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtwordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwordKeyPressed

    private void txtwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtwordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwordKeyTyped

//    public void cargaComboLetras()
//    {
//        
//        try
//        {
//            jComboBoxLetra.removeAllItems();
//            Nodo aux = VtnPrincipal.raiz.getSiguiente();
//            
//            do
//            {
//                jComboBoxLetra.addItem(aux.getEtiqueta());
//                aux = aux.getSiguiente();
//            } while (aux != VtnPrincipal.raiz.getSiguiente());
//
//            if (jComboBoxLetra.getItemCount() == 0)
//            {
//                Mensaje.error(this, "there are no letters in alphabet");
//                this.dispose();
//            } else
//            {
//                jComboBoxLetra.setSelectedIndex(0);
//
//            }
//        } catch (Exception e)
//        {
//            Mensaje.error(this, "there are no letters in alphabet");
//            System.out.println("Error.." + e.toString());
//        }
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnAltaConceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnAltaConceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnAltaConceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnAltaConceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnAltaConceptos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelLetra;
    private javax.swing.JLabel JLabelLetra1;
    private javax.swing.JLabel JLabelLetra2;
    private javax.swing.JLabel JLabelLetra3;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDefin;
    private javax.swing.JTextField jTextFieldExample;
    private javax.swing.JTextField txtconcepts;
    private javax.swing.JTextField txtword;
    // End of variables declaration//GEN-END:variables
}
